name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    uses: bobleesj/release-scripts/.github/workflows/_matrix-and-codecov-on-merge-to-main.yml@ci-linux
    with:
      project: diffpy.fourigui
      c_extension: false
      headless: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
